services:
  minio:
    container_name: sdc.minio
    image: "minio/minio:latest"
    environment:
      - "MINIO_ROOT_USER=${MINIO_ROOT_USER}"
      - "MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}"
    volumes:
      - "./data/minio:/data/minio"
    ports:
      - "5100:9000" # minio server
      - "5101:9001" # web console
    command: server /data/minio --console-address ":9001"
    networks:
      - sdc.net
  minio-init:
    container_name: sdc.minio.init
    build:
      context: .
      dockerfile: ./packages/minio-init/Dockerfile
    environment:
      - "MINIO_ROOT_USER=${MINIO_ROOT_USER}"
      - "MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}"
      - "MINIO_API_URL=http://sdc-minio:9000" # uses the 'sdc-net' network
    networks:
      - sdc.net
networks:
  sdc.net:
  # web:
  #   container_name: sdc-web
  #   build:
  #     context: .
  #     target: prod
  #     dockerfile: ./packages/web/Dockerfile
  #   environment:
  #     - "SITE_URL=${SITE_URL}"
  #   image: "sdc-web"
  #   ports:
  #     - "5100:8080"
  #   volumes:
  #     - "./data/sqlite.db:/app/sqlite.db"
  #     - "./data/logs:/app/logs"
  #   restart: on-failure
  #   networks:
  #     - spencerduballcom-net
