services:
  libsql:
    container_name: spencerduballcom-libsql
    image: "ghcr.io/tursodatabase/libsql-server:latest"
    platform: linux/amd64
    ports:
      - "5120:8080" # The HTTP API
      - "5121:5001" # The gRPC API
    environment:
      - "SQLD_NODE=primary"
    volumes:
      - ./data/libsql:/var/lib/sqld
    restart: on-failure
    networks:
      - spencerduballcom_net
  minio:
    container_name: spencerduballcom-minio
    image: "minio/minio:latest"
    ports:
      - "5130:9000" # The S3 API
      - "5131:9001" # The web console
    environment:
      - "MINIO_ROOT_USER=admin"
      - "MINIO_ROOT_PASSWORD=password"
    volumes:
      - ./data/minio:/data
    command: "server /data --console-address ':9001'"
    restart: on-failure
    networks:
      - spencerduballcom_net
networks:
  spencerduballcom_net:
