import type { NextPage } from "next";
import Head from "next/head";
import { Grid, GridProps, Container } from "@chakra-ui/react";
import { Header } from "components/header/header";
import { ProfileCard } from "components/profile-card/profile-card";

const Main = (props: GridProps) => {
  return (
    <Grid {...props}>
      <Container maxW="container.lg">
        <ProfileCard />
      </Container>
    </Grid>
  );
};

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid gap={8}>
        <Header />
        <Main />
      </Grid>
    </>
  );
};

export default Home;
